<?php
/**
 * @category  Template
 * @package   Task_Executor
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2018 Agence Dn'D
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */
?>
<input id="option-<?php echo $this->getName() ?>" type="hidden" name="<?php echo $this->getName() ?>" value="<?php echo $this->getDefault() ?>" />