<?php
/**
 * @category  Template
 * @package   Task_Executor
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2018 Agence Dn'D
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */
?>
<span class="label"><?php echo $this->getLabel() ?></span>
<div class="task-option">
    <?php foreach($this->getOptions() as $key => $select): ?>
        <input id="option-<?php echo $this->getName() ?>-<?php echo $key ?>" type="radio" name="<?php echo $this->getName() ?>" value="<?php echo $select['value'] ?>"<?php if ($this->getDefault() == $select['value']): ?> checked="checked"<?php endif; ?> />
        <label for="option-<?php echo $this->getName() ?>-<?php echo $key ?>"><?php echo $select['label'] ?></label>
    <?php endforeach; ?>
    <?php if ($this->getComment()): ?>
        <span class="option-comment">
        <?php echo $this->getComment() ?>
    </span>
    <?php endif; ?>
</div>