<?php
/**
 * @category  Template
 * @package   Task_Executor
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2018 Agence Dn'D
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */
?>
<label class="label" for="option-<?php echo $this->getName() ?>"><?php echo $this->getLabel() ?></label>
<div class="task-option">
    <select id="option-<?php echo $this->getName() ?>" name="<?php echo $this->getName() ?>">
        <?php foreach($this->getOptions() as $select): ?>
            <option value="<?php echo $select['value'] ?>"<?php if ($this->getDefault() == $select['value']): ?> selected="selected"<?php endif; ?>><?php echo $select['label'] ?></option>
        <?php endforeach; ?>
    </select>
    <?php if ($this->getComment()): ?>
        <span class="option-comment">
        <?php echo $this->getComment() ?>
    </span>
    <?php endif; ?>
</div>