<?php
/**
 * @category  Template
 * @package   Task_Executor
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2018 Agence Dn'D
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */
?>
<?php if ($this->getValue('comment')): ?>
    <p class="task-comment"><?php echo $this->getValue('comment') ?></p>
<?php endif; ?>

<?php echo $this->getChildHtml() ?>

<?php $options = $this->getValue('options') ?>

<?php if ($options): ?>
    <div id="task-select-options">
        <?php foreach ($options as $option): ?>
            <?php echo $this->getRenderer($option) ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>